id: I0747C2F3
legacy_id: P009448
ocr_import_info:
  bdrc_scan_id: W25577
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T05:33:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:13:00.886372+00:00'
last_modified: 2022-09-02 14:13:06.664213
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W25577
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW25577
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱམས་ཆེན་ཆོས་རྗེའི་རྣམ་ཐར།
statistics:
  ocr_word_mean_confidence_index: 0.6033855676758535
  ocr_word_median_confidence_index: 0.5899999737739563
quality: null
bases:
  I1KG3759:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3759
      total_pages: 50
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3759.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.6033855676758535
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
