id: P009448
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W25577
  title: བྱམས་ཆེན་ཆོས་རྗེའི་རྣམ་ཐར
  author: ''
  volumes:
    85c2502762f24e10ad8d5c030868fc44:
      image_group_id: I1KG3759
      title: ''
      volume_number: 1
      total_pages: 50
      base_file: v001.txt
